// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owsideuxsocpqsvpyzxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93c2lkZXV4c29jcHFzdnB5enhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTAxMzcsImV4cCI6MjA2ODIyNjEzN30.rN9QSdOfTzbF6wXeMMhHg6R0juswZxtzg7q1-xUa4jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});